In [25]:
import pandas as pd

In [26]:
combined_df = pd.read_csv('./Year_Released Title and Metacritic Rating.csv')
imdb_db = pd.read_csv('./imdb_db.csv')

In [27]:
imdb_db = imdb_db[['primaryTitle','averageRating','startYear']]
imdb_db = pd.DataFrame(imdb_db)
imdb_db.columns = ['Title','Imdb Rating','Year']

In [28]:
combined_df = combined_df.loc[combined_df['Year'] != 'TBA']

In [29]:
combined = pd.merge(combined_df,imdb_db,how='inner',on = 'Title')

In [30]:
combined['Year_x'] = combined['Year_x'].astype(int)
combined['Year_y'] = combined['Year_y'].astype(int)

In [31]:
combined = combined[combined['Year_x'] == combined['Year_y']]

In [35]:
combined = combined.drop(columns ='Year_y')
combined.columns = ['Title','Year','Metacritic Rating','Netflix','Amazon','Hulu','Imdb Rating']

KeyError: "['Year_y'] not found in axis"

In [38]:
combined.reset_index(drop=True)

,Title,Year,Metacritic Rating,Netflix,Amazon,Hulu,Imdb Rating
0,Citizen Kane,1941,100,NaN,NaN,NaN,8.3
1,The Godfather,1972,100,NaN,NaN,NaN,9.2
2,Rear Window,1954,100,NaN,NaN,NaN,8.5
3,Boyhood,2014,100,NaN,NaN,NaN,7.9
4,Three Colors: Red,1994,100,NaN,NaN,NaN,8.1
5,Vertigo,1958,100,NaN,NaN,NaN,8.3
6,Notorious,1946,100,NaN,NaN,NaN,8.0
7,Singin' in the Rain,1952,100,NaN,NaN,NaN,8.3
8,Moonlight,2016,100,NaN,NaN,NaN,7.4
9,Pinocchio,1940,100,NaN,NaN,NaN,7.5
10,Touch of Evil,1958,100,NaN,NaN,NaN,8.0
11,The Treasure of the Sierra Madre,1948,100,NaN,NaN,NaN,8.2
12,Pan's Labyrinth,2006,100,NaN,NaN,NaN,8.2
13,North by Northwest,1959,100,NaN,NaN,NaN,8.3
14,All About Eve,1950,100,NaN,NaN,NaN,8.3
15,Hoop Dreams,1994,99,NaN,NaN,NaN,8.3
16,The Third Man,1949,99,NaN,NaN,NaN,8.2
17,Dr. Strangelove or: How I Learned to Stop Worr...,1964,99,NaN,NaN,NaN,8.4
18,Some Like It Hot,1959,99,NaN,NaN,NaN,8.2
19,Psycho,1960,99,NaN,NaN,NaN,8.5
20,American Graffiti,1973,98,NaN,NaN,NaN,7.5
21,Dumbo,1941,98,NaN,NaN,NaN,7.3
22,Roma,2018,98,NaN,NaN,NaN,7.8
23,Ran,1985,98,NaN,NaN,NaN,8.2
24,12 Angry Men,1957,98,NaN,NaN,NaN,8.9
25,Manchester by the Sea,2016,98,NaN,NaN,NaN,7.8
26,Rosemary's Baby,1968,98,NaN,NaN,NaN,8.0
27,The Maltese Falcon,1941,98,NaN,NaN,NaN,8.1
28,12 Years a Slave,2013,98,NaN,NaN,NaN,8.1
29,Nashville,1975,98,NaN,NaN,NaN,7.8
...,...,...,...,...,...,...,...
615,The Hate U Give,2018,86,NaN,NaN,NaN,7.3
616,At Berkeley,2013,86,NaN,NaN,NaN,7.3
617,Blade Runner 2049,2017,86,NaN,NaN,NaN,8.0
618,Step,2017,86,NaN,NaN,NaN,6.8
619,Experimenter,2015,86,NaN,NaN,NaN,6.6
620,The Revolution Will Not Be Televised,2003,86,NaN,NaN,NaN,8.4
621,A History of Violence,2005,86,NaN,NaN,NaN,7.5
622,A Mighty Wind,2003,86,NaN,NaN,NaN,7.3
623,The Damned United,2009,86,NaN,NaN,NaN,7.6
624,Georgia,1995,86,NaN,NaN,NaN,6.5
625,Fresh,1994,86,NaN,NaN,NaN,7.6
626,Arrival,2016,86,NaN,NaN,NaN,7.9
627,Juno,2007,86,NaN,NaN,NaN,7.5
628,Blue Valentine,2010,86,NaN,NaN,NaN,7.4
629,Master and Commander: The Far Side of the World,2003,86,NaN,NaN,NaN,7.4
630,Four Weddings and a Funeral,1994,86,NaN,NaN,NaN,7.1
631,Top Five,2014,86,NaN,NaN,NaN,6.4
632,Pete Seeger: The Power of Song,2007,86,NaN,NaN,NaN,8.3
633,Living in Oblivion,1995,86,NaN,NaN,NaN,7.5
634,Coco,2017,86,NaN,NaN,NaN,8.4
635,Coco,2017,86,NaN,NaN,NaN,7.4
636,Bridge of Spies,2015,86,NaN,NaN,NaN,7.6
637,Driving Miss Daisy,1989,86,NaN,NaN,NaN,7.4
638,Shaun the Sheep Movie,2015,86,NaN,NaN,NaN,7.4
639,The Station Agent,2003,85,NaN,NaN,NaN,7.7
640,Foxcatcher,2014,85,NaN,NaN,NaN,7.0
641,Dolores,2017,85,NaN,NaN,NaN,7.0
642,Twinsters,2015,85,NaN,NaN,NaN,7.6
643,The China Syndrome,1979,85,NaN,NaN,NaN,7.4
644,Bright Star,2009,85,NaN,NaN,NaN,7.0

In [34]:
combined.to_csv(index =False, path_or_buf = './Metacritic and IMDB.csv')