In [10]:
import pandas as pd

In [11]:
combined_df = pd.read_csv('./Year_Released Title and Metacritic Rating.csv')
imdb_db = pd.read_csv('./imdb_db.csv')

In [12]:
imdb_db = imdb_db[['primaryTitle','averageRating','startYear']]
imdb_db = pd.DataFrame(imdb_db)
imdb_db.columns = ['Title','Imdb Rating','Year']

In [13]:
combined_df = combined_df.loc[combined_df['Year'] != 'TBA']

C:\Users\ Derek\anaconda\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [14]:
combined = pd.merge(combined_df,imdb_db,how='inner',on = 'Title')

In [15]:
combined['Year_x'] = combined['Year_x'].astype(int)
combined['Year_y'] = combined['Year_y'].astype(int)

In [16]:
combined = combined[combined['Year_x'] == combined['Year_y']]

In [24]:
combined = combined.drop(columns ='Year_y')
combined.columns = ['Title','Year','Metacritic Rating','Netflix','Amazon','Hulu','Imdb Rating']
combined.head()

KeyError: "['Year_y'] not found in axis"

,Title,Year_x,Metacritic Rating,Netflix,Amazon,Hulu,Imdb Rating
0,Citizen Kane,1941,100,NaN,NaN,NaN,8.3
1,The Godfather,1972,100,NaN,NaN,NaN,9.2
2,Rear Window,1954,100,NaN,NaN,NaN,8.5
6,Boyhood,2014,100,NaN,NaN,NaN,7.9
7,Three Colors: Red,1994,100,NaN,NaN,NaN,8.1
8,Vertigo,1958,100,NaN,NaN,NaN,8.3
9,Notorious,1946,100,NaN,NaN,NaN,8.0
11,Singin' in the Rain,1952,100,NaN,NaN,NaN,8.3
14,Moonlight,2016,100,NaN,NaN,NaN,7.4
15,Pinocchio,1940,100,NaN,NaN,NaN,7.5
24,Touch of Evil,1958,100,NaN,NaN,NaN,8.0
25,The Treasure of the Sierra Madre,1948,100,NaN,NaN,NaN,8.2
26,Pan's Labyrinth,2006,100,NaN,NaN,NaN,8.2
27,North by Northwest,1959,100,NaN,NaN,NaN,8.3
28,All About Eve,1950,100,NaN,NaN,NaN,8.3
29,Hoop Dreams,1994,99,NaN,NaN,NaN,8.3
31,The Third Man,1949,99,NaN,NaN,NaN,8.2
32,Dr. Strangelove or: How I Learned to Stop Worr...,1964,99,NaN,NaN,NaN,8.4
37,Some Like It Hot,1959,99,NaN,NaN,NaN,8.2
39,Psycho,1960,99,NaN,NaN,NaN,8.5
43,American Graffiti,1973,98,NaN,NaN,NaN,7.5
45,Dumbo,1941,98,NaN,NaN,NaN,7.3
49,Roma,2018,98,NaN,NaN,NaN,7.8
50,Ran,1985,98,NaN,NaN,NaN,8.2
51,12 Angry Men,1957,98,NaN,NaN,NaN,8.9
52,Manchester by the Sea,2016,98,NaN,NaN,NaN,7.8
53,Rosemary's Baby,1968,98,NaN,NaN,NaN,8.0
56,The Maltese Falcon,1941,98,NaN,NaN,NaN,8.1
57,12 Years a Slave,2013,98,NaN,NaN,NaN,8.1
58,Nashville,1975,98,NaN,NaN,NaN,7.8
...,...,...,...,...,...,...,...
1497,The Hate U Give,2018,86,NaN,NaN,NaN,7.3
1498,At Berkeley,2013,86,NaN,NaN,NaN,7.3
1499,Blade Runner 2049,2017,86,NaN,NaN,NaN,8.0
1500,Step,2017,86,NaN,NaN,NaN,6.8
1501,Experimenter,2015,86,NaN,NaN,NaN,6.6
1513,The Revolution Will Not Be Televised,2003,86,NaN,NaN,NaN,8.4
1514,A History of Violence,2005,86,NaN,NaN,NaN,7.5
1515,A Mighty Wind,2003,86,NaN,NaN,NaN,7.3
1516,The Damned United,2009,86,NaN,NaN,NaN,7.6
1518,Georgia,1995,86,NaN,NaN,NaN,6.5
1520,Fresh,1994,86,NaN,NaN,NaN,7.6
1523,Arrival,2016,86,NaN,NaN,NaN,7.9
1525,Juno,2007,86,NaN,NaN,NaN,7.5
1526,Blue Valentine,2010,86,NaN,NaN,NaN,7.4
1528,Master and Commander: The Far Side of the World,2003,86,NaN,NaN,NaN,7.4
1529,Four Weddings and a Funeral,1994,86,NaN,NaN,NaN,7.1
1531,Top Five,2014,86,NaN,NaN,NaN,6.4
1532,Pete Seeger: The Power of Song,2007,86,NaN,NaN,NaN,8.3
1539,Living in Oblivion,1995,86,NaN,NaN,NaN,7.5
1541,Coco,2017,86,NaN,NaN,NaN,8.4
1542,Coco,2017,86,NaN,NaN,NaN,7.4
1544,Bridge of Spies,2015,86,NaN,NaN,NaN,7.6
1545,Driving Miss Daisy,1989,86,NaN,NaN,NaN,7.4
1547,Shaun the Sheep Movie,2015,86,NaN,NaN,NaN,7.4
1549,The Station Agent,2003,85,NaN,NaN,NaN,7.7
1550,Foxcatcher,2014,85,NaN,NaN,NaN,7.0
1554,Dolores,2017,85,NaN,NaN,NaN,7.0
1555,Twinsters,2015,85,NaN,NaN,NaN,7.6
1559,The China Syndrome,1979,85,NaN,NaN,NaN,7.4
1560,Bright Star,2009,85,NaN,NaN,NaN,7.0