In [26]:
import pandas as pd

In [27]:
titles = pd.read_csv('./Year_Released and Title.csv')
mc_scores = pd.read_csv("./Metacritic Rating.csv")
imdb_db = pd.read_csv('./imdb_db.csv')

In [28]:
imdb_db = imdb_db[['primaryTitle','averageRating','startYear']]
imdb_db = pd.DataFrame(imdb_db)
imdb_db.columns = ['Title','Imdb Rating','Year']
titles = titles[['Title','Year']]

In [29]:
mc_scores = pd.DataFrame(mc_scores['0'])

In [30]:
combined_df = pd.merge(titles,mc_scores, right_index = True, left_index = True)

combined_df.columns = ['Title','Year','MC_Rating']
combined_df = combined_df[['Title','MC_Rating','Year']]
combined_df.head()

           Title  MC_Rating  Year
0   Citizen Kane        100  1941
1  The Godfather        100  1972
2    Rear Window        100  1954
3     Casablanca        100  1943
4        Boyhood        100  2014

In [31]:
combined_df = combined_df.loc[combined_df['Year'] != 'TBA']

In [32]:
combined = pd.merge(combined_df,imdb_db,how='inner',on = 'Title')

In [33]:
combined['Year_x'] = combined['Year_x'].astype(int)
combined['Year_y'] = combined['Year_y'].astype(int)

In [34]:
combined = combined[combined['Year_x'] == combined['Year_y']]

In [35]:
combined

,Title,MC_Rating,Year_x,Imdb Rating,Year_y
0,Citizen Kane,100,1941,8.3,1941
1,The Godfather,100,1972,9.2,1972
2,Rear Window,100,1954,8.5,1954
6,Boyhood,100,2014,7.9,2014
7,Three Colors: Red,100,1994,8.1,1994
8,Vertigo,100,1958,8.3,1958
9,Notorious,100,1946,8.0,1946
11,Singin' in the Rain,99,1952,8.3,1952
14,Moonlight,99,2016,7.4,2016
15,Pinocchio,99,1940,7.5,1940
24,Touch of Evil,99,1958,8.0,1958
25,The Treasure of the Sierra Madre,98,1948,8.2,1948
26,Pan's Labyrinth,98,2006,8.2,2006
27,North by Northwest,98,1959,8.3,1959
28,All About Eve,98,1950,8.3,1950
29,Hoop Dreams,98,1994,8.3,1994
31,The Third Man,97,1949,8.2,1949
32,Dr. Strangelove or: How I Learned to Stop Worr...,97,1964,8.4,1964
37,Some Like It Hot,97,1959,8.2,1959
39,Psycho,97,1960,8.5,1960
43,American Graffiti,97,1973,7.5,1973
45,Dumbo,96,1941,7.3,1941
49,Roma,96,2018,7.8,2018
50,Ran,96,1985,8.2,1985
51,12 Angry Men,96,1957,8.9,1957
52,Manchester by the Sea,96,2016,7.8,2016
53,Rosemary's Baby,96,1968,8.0,1968
56,The Maltese Falcon,96,1941,8.1,1941
57,12 Years a Slave,96,2013,8.1,2013
58,Nashville,96,1975,7.8,1975
...,...,...,...,...,...
1495,At Berkeley,81,2013,7.3,2013
1496,Blade Runner 2049,81,2017,8.0,2017
1497,Step,81,2017,6.8,2017
1498,Experimenter,81,2015,6.6,2015
1510,The Revolution Will Not Be Televised,81,2003,8.4,2003
1511,A History of Violence,81,2005,7.5,2005
1512,A Mighty Wind,81,2003,7.3,2003
1513,The Damned United,81,2009,7.6,2009
1515,Georgia,81,1995,6.5,1995
1517,Fresh,81,1994,7.6,1994
1520,Arrival,81,2016,7.9,2016
1522,Juno,81,2007,7.5,2007
1523,Blue Valentine,81,2010,7.4,2010
1525,Master and Commander: The Far Side of the World,81,2003,7.4,2003
1526,Four Weddings and a Funeral,81,1994,7.1,1994
1528,Top Five,81,2014,6.4,2014
1529,Pete Seeger: The Power of Song,81,2007,8.3,2007
1536,Living in Oblivion,81,1995,7.5,1995
1538,Coco,81,2017,8.4,2017
1539,Coco,81,2017,7.4,2017
1541,Bridge of Spies,81,2015,7.6,2015
1542,Driving Miss Daisy,81,1989,7.4,1989
1544,Shaun the Sheep Movie,81,2015,7.4,2015
1547,The Station Agent,81,2003,7.7,2003
1548,Foxcatcher,81,2014,7.0,2014
1552,Dolores,81,2017,7.0,2017
1553,Twinsters,81,2015,7.6,2015
1557,The China Syndrome,81,1979,7.4,1979
1558,Bright Star,81,2009,7.0,2009
1561,Halloween,81,1978,7.8,1978